# This file was generated by GoReleaser. DO NOT EDIT.
cask "kamu" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "3cdc92c813ec55dbf74ce3055a6e1e891edf39c36c485926dea32e5685150259"
      url "https://github.com/kotisivukamu/kamu-cli/releases/download/v#{version}/kamu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a33a5b296b3d6594d8a48735ad0453d201f6bd336ff27f3c4ee08d41c976cc85"
      url "https://github.com/kotisivukamu/kamu-cli/releases/download/v#{version}/kamu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6435aa9fa58a6264d7d643f81eece0348971c63135c8cfdab7f36ccd428bd5d0"
      url "https://github.com/kotisivukamu/kamu-cli/releases/download/v#{version}/kamu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ffa1f4915f469ecd7f1583bf90e41e7e28b6769d9d992bf9107420b0839d536f"
      url "https://github.com/kotisivukamu/kamu-cli/releases/download/v#{version}/kamu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kamu"
  desc "Unified CLI for the Kamu platform — drive kamudb, kamubee, and kamudns with one auth"
  homepage "https://github.com/kotisivukamu/kamu-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kamu"

  # No zap stanza required

end
