# This file was generated by GoReleaser. DO NOT EDIT.
cask "kamu" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "356dab7e3ed088cefc7293c7f3c4064387a85ac7d2fe03948c8c6b2c6a8d3710"
      url "https://github.com/kotisivukamu/kamucli/releases/download/v#{version}/kamu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "596c148c8a4d37b6a494d8d15bdcf448f3385025953110cd5878ed7647ecaef2"
      url "https://github.com/kotisivukamu/kamucli/releases/download/v#{version}/kamu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "457536b44eb94142efe72759a38abdf74490ed6e6de1bb43bb82f7a3fbd087df"
      url "https://github.com/kotisivukamu/kamucli/releases/download/v#{version}/kamu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5db2b3039a9f1bd1d3d40a655a3851ad92161bf2e0d6dcd1582171f5a43bf0d"
      url "https://github.com/kotisivukamu/kamucli/releases/download/v#{version}/kamu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kamu"
  desc "Unified CLI for the Kamu platform — drive kamudb, kamubee, and kamudns with one auth"
  homepage "https://github.com/kotisivukamu/kamucli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kamu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kamu"]
    end
  end

  # No zap stanza required
end
