# This file was generated by GoReleaser. DO NOT EDIT.
cask "kamu" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "7475b37dc12e82a474bff822d4fd0131ca7b4f74328ceca761981e3c1d91fbb6"
      url "https://github.com/kotisivukamu/kamucli/releases/download/v#{version}/kamu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "47f8f9ce3cfbbbcead3d7f69aa9f0fafbf80290214c018c1a934ec50f3f5c4bf"
      url "https://github.com/kotisivukamu/kamucli/releases/download/v#{version}/kamu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f39ea0c806868513e6779cbd3025307ad3597a63fb91ffe19315f166b735775a"
      url "https://github.com/kotisivukamu/kamucli/releases/download/v#{version}/kamu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "95f1688fc23d03e68db84fc9080e8eab50323c9e640d57a0cde5d0f741e4aa71"
      url "https://github.com/kotisivukamu/kamucli/releases/download/v#{version}/kamu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kamu"
  desc "Unified CLI for the Kamu platform — drive kamudb, kamubee, and kamudns with one auth"
  homepage "https://github.com/kotisivukamu/kamucli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kamu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kamu"]
    end
  end

  # No zap stanza required
end
