# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kamu < Formula
  desc "Unified CLI for the Kamu platform — drive kamudb, kamubee, and kamudns with one auth"
  homepage "https://github.com/kotisivukamu/kamu-cli"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kotisivukamu/kamu-cli/releases/download/v0.2.1/kamu_0.2.1_darwin_amd64.tar.gz"
      sha256 "bc1d0375a7b861c0257eea27887545172b4f219b32e1e6fb41c3b2f90809241e"

      define_method(:install) do
        bin.install "kamu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kotisivukamu/kamu-cli/releases/download/v0.2.1/kamu_0.2.1_darwin_arm64.tar.gz"
      sha256 "f5537642ef60391a7c637f744ac5465ca09fb0ddbc1824e3127083bd20081eb9"

      define_method(:install) do
        bin.install "kamu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kotisivukamu/kamu-cli/releases/download/v0.2.1/kamu_0.2.1_linux_amd64.tar.gz"
      sha256 "54151a49a2950b8ce88702e940291b4b2cc4fafd35d82ad5318e6fcfda15a0c1"
      define_method(:install) do
        bin.install "kamu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kotisivukamu/kamu-cli/releases/download/v0.2.1/kamu_0.2.1_linux_arm64.tar.gz"
      sha256 "18fcfc03379f68f0017331943b01dcc45e071d07e36938b6d3610b9e08ac06da"
      define_method(:install) do
        bin.install "kamu"
      end
    end
  end

  test do
    assert_match "kamu", shell_output("#{bin}/kamu version")
  end
end
