# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kamu < Formula
  desc "Unified CLI for the Kamu platform — drive kamudb, kamubee, and kamudns with one auth"
  homepage "https://github.com/kotisivukamu/kamu-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kotisivukamu/kamu-cli/releases/download/v0.2.0/kamu_0.2.0_darwin_amd64.tar.gz"
      sha256 "796c9518e8fee12ccbb29bf8c08f6e28b3cae27ead548c1e94c0441b310e5073"

      define_method(:install) do
        bin.install "kamu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kotisivukamu/kamu-cli/releases/download/v0.2.0/kamu_0.2.0_darwin_arm64.tar.gz"
      sha256 "0850c68c81bbc6c62790facb4d7ba858c2a20455f4c72278299784a3425a605f"

      define_method(:install) do
        bin.install "kamu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kotisivukamu/kamu-cli/releases/download/v0.2.0/kamu_0.2.0_linux_amd64.tar.gz"
      sha256 "751bdb58be4418e82c1c999e35d0d8174a93b98a4a2a141b8846ac2d2334ece6"
      define_method(:install) do
        bin.install "kamu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kotisivukamu/kamu-cli/releases/download/v0.2.0/kamu_0.2.0_linux_arm64.tar.gz"
      sha256 "07ff0fe5845dd1854549fafd9c97a0d39042f50d7226cd5c27cd01985643dc27"
      define_method(:install) do
        bin.install "kamu"
      end
    end
  end

  test do
    assert_match "kamu", shell_output("#{bin}/kamu version")
  end
end
